### ISSUE TITLE
TeslaMate no longer compiles with Elixir 1.18.4+ / OTP 28

### ISSUE THREAD

**Issue by swiffer** [teslamate-org/teslamate#5505]
### Is there an existing issue for this?

- [x] I have checked the existing issues and discussions, and I can confirm that there are no duplicates.

### What happened?

This code no longer compiles with Elixir 1.18.4+ / OTP 28 as it's emitting a warning

https://github.com/teslamate-org/teslamate/blob/7054517c10475f39f480edeae8f90c6f717985a3/lib/tesla_api/error.ex#L127

### Expected Behavior

Either compile correctly or we should rephrase support ambitions again in:

https://docs.teslamate.org/docs/development#requirements

### Can the issue reliably be reproduced?

Yes

### Relevant log output

```shell
Generating TeslaMateWeb.Cldr for 20 locales named [:ca, :da, :de, :en, :es, ...] with a default locale named :en
     warning: Inspect.Map.inspect_as_struct/4 is undefined or private. Did you mean:
           * inspect/4
           * inspect/2
     │
 127 │     |> Inspect.Map.inspect_as_struct("TeslaApi.Error", fields, opts)
     │                    ~
     │
     └─ lib/tesla_api/error.ex:127:20: Inspect.TeslaApi.Error.inspect/2
Compilation failed due to warnings while using the --warnings-as-errors option
```

### Type of installation

Docker (https://docs.teslamate.org/docs/installation/docker/)

### Version

4.1.0-dev

### PostgreSQL version

18.4

### Are you running latest major supported PostgreSQL version?

- [x] I run the latest major supported PostgreSQL version

### Are you using a reverse Proxy for TeslaMate?

Yes (specify in next field)

### Details about your reverse Proxy if applicable

Traefik

**Comment by JakobLichterfeld** [comment]
Ah, you are right, we say please use

> Elixir >= 1.19.5-otp-28

But we support down to 1.18.4 which isn't correct anymore.
